### ISSUE TITLE
Generated dependency results in inability to call backend

### ISSUE THREAD

**Issue by sknick** [peuter/protoc-gen-qx#32]
If I don't use `skipDeps` when generating code, I end up with an altered version of `google-protobuf.js` that results in my application never being able to make a call to any gRPC APIs. I get this mystifying error, with the backend logging 0 problems and status codes of `OK` for each request: `Response closed without grpc-status (Headers only) (code 2)`

Analyzing the diff (which is difficult since the file is minified), I notice that a large section of code in *my* version of the `google-protobuf.js` file is missing--specifically, the definition of several wrapper types:

![image](https://user-images.githubusercontent.com/6498506/216775667-b4b6c9fb-6247-46ee-9e71-ce0b4940e762.png)

 So the question I guess is, why is that stuff missing? Also, is it responsible for the strange error message I mentioend above in the client?

Would love to at least hear your thoughts on this. Perhaps I need to alter how I'm doing something but I'm not sure.

**Comment by peuter** [comment]
So this is about the wrappers_pb that are missing right? I guess you have to find away to manipulate the original webpack configuration to include them and maybe introduce a new configuration option for that. The `require` option i only for stuff needed at compile time, not for something that is need at runtime.
I guess the error you see is the result of a malformed grpc request, most likely because those types are missing. But I still wonder why the generator does not show an error.

If you want to figure out a new configuration option for that, this is the spot in the code where this files are generated:
https://github.com/gonicus/protoc-gen-qx/blob/master/index.js#L220-L246
Maybe its enough to have a local webpack.config.js that is merged into (or replaces) the existing one to be able to customize things?

**Comment by sknick** [comment]
OK, I'll give it some thought and try to come up with a PR. I'll close this for now.
